<?php

echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n";

echo "
<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.1//EN\"
\"http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd\">


<html xmlns='http://www.w3.org/1999/xhtml' xmlns:v='urn:schemas-microsoft-com:vml'>
	<head>
		<meta http-equiv='content-type' content='$contenttype; charset=UTF-8'/>
		<meta name='keywords' content='rpg,roleplaying games,heraldry,name generator,coat of arms' />
		<title>$setting[title]</title>
		$css
		<link rel='shortcut icon' href='/headers/img/favicon.png' type='image/x-icon' />
		<script type='text/javascript'>

		  var _gaq = _gaq || [];
		  _gaq.push(['_setAccount', 'UA-19664217-1']);
		  _gaq.push(['_trackPageview']);
		
		  (function() {
		    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
		    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
		    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
		  })();

		</script>
	</head>

	<body$bdload>
	";

?>
