<?php

class charge {
    private $detail = Array(
        "base",     //Base colour
        "armed",    // Claws and teeth
        "langued",  // Tongue
        "pizzled",  // Genitals
        "attired",  // 
        "unguled",  // 
        "crined",   // 
        "fructed",  // Fruits
        "leaved",   // Leaves
        "barbed",   // 
        "incensed", // 
        "flammant", // Fire
        );
    
    
    
    
}

?>